name: Issue to PR

on:
  issues:
    types: [opened]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  generate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get issue details
        id: issue
        run: |
          echo "ISSUE_TITLE=$(echo '${{ github.event.issue.title }}' | sed 's/ /_/g')" >> $GITHUB_ENV
          echo "ISSUE_BODY<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Generate code change using Copilot
        run: |
          echo "Generating code change for issue: $ISSUE_TITLE"
          echo "$ISSUE_BODY" > issue_description.txt
          bash ./generate_change.sh issue_description.txt
        shell: bash

      - name: Commit changes
        run: |
          BRANCH_NAME="issue-${{ github.event.issue.number }}"
          git checkout -b "$BRANCH_NAME"
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Fix: Address issue #${{ github.event.issue.number }} - $ISSUE_TITLE"
          git push origin "$BRANCH_NAME"

      - name: Create pull request
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Fix: ${process.env.ISSUE_TITLE}`,
              head: `issue-${{ github.event.issue.number }}`,
              base: 'main',
              body: `This PR addresses issue #${{ github.event.issue.number }}\n\n${{ github.event.issue.body }}`
            });
            console.log(`Created PR: ${pr.html_url}`);
